package MessageType;

public enum InGameMessageType implements MessageType {
	CATAGORY_SELECTION_ANNOUNCEMENT,CATAGORY_SELECTION,QUESTION,ANSWER,BUZZ,BUZZ_RESULT,
	SCOREBOARD,ANSWER_RESULT,SCREW,SCREW_RESULT
}
